server:
  port: 8082

logging:
  level:
    root: WARN
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management

spring:
  application:
    name: backend-challenge
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:itausegdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 0password

  h2:
    console:
      enable: true
      path: /console-h2